# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43ac9320290b2121b8687d730936d7d14fb249ad355dd659bdb8a78b9e20552110902c6d150e421acdd6c62493ca19d564e6736771e23097326eff61e57d0bbe

test:
  secret_key_base: 7d1ca622baf91f8cb7b3675a6bc036e49708ca3aa53319c228cedb60f37b4eddde879e9f1a1a7aafb565f2a52e280a585430b9bf2566fab14423155563a173c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
